apiVersion: v1
kind: Namespace
metadata:
  name: loanbroker-example
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: loanbroker-bank1
  namespace: loanbroker-example
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BANK_ID
          value: Bank1
        - name: MAX_LOAN_AMOUNT
          value: "500000"
        - name: MIN_CREDIT_SCORE
          value: "300"
        - name: BASE_RATE
          value: "3"
        image: dev.local/loanbroker-bank:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: loanbroker-bank2
  namespace: loanbroker-example
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BANK_ID
          value: Bank2
        - name: MAX_LOAN_AMOUNT
          value: "65536"
        - name: MIN_CREDIT_SCORE
          value: "100"
        - name: BASE_RATE
          value: "2"
        image: dev.local/loanbroker-bank:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: loanbroker-bank3
  namespace: loanbroker-example
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BANK_ID
          value: Bank3
        - name: MAX_LOAN_AMOUNT
          value: "10000"
        - name: MIN_CREDIT_SCORE
          value: "400"
        - name: BASE_RATE
          value: "2"
        image: dev.local/loanbroker-bank:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: loanbroker-credit-bureau
  namespace: loanbroker-example
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - image: dev.local/loanbroker-credit-bureau:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 0
          successThreshold: 1
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
---
# trigger for the Bank Function
# remove it once kn func implements this feature
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-aggregator-bank1-quote
  namespace: loanbroker-example
spec:
  broker: default
  filter:
    attributes:
      type: kogito.serverless.workflow.request.quote
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: loanbroker-bank1
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-aggregator-bank2-quote
  namespace: loanbroker-example
spec:
  broker: default
  filter:
    attributes:
      type: kogito.serverless.workflow.request.quote
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: loanbroker-bank2
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-aggregator-bank3-quote
  namespace: loanbroker-example
spec:
  broker: default
  filter:
    attributes:
      type: kogito.serverless.workflow.request.quote
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: loanbroker-bank3
