# Trigger for the UI, will receive the final response from the flow
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-ui-loanbroker
spec:
  broker: default
  filter:
    attributes:
      type: kogito.serverless.workflow.aggregated.quotes
  subscriber:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: loanbroker-ui

